POST http://localhost:5000/api/v1/auth/login/admin
Content-Type: application/json

{
    "username": "admin",
    "pass": "admin"
}

###
DELETE  http://localhost:5000/logout

###
POST http://localhost:5000/api/v1/auth/register/admin
Content-Type: application/json

{
    "username": "Admin",
    "pass": "admin",
    "name": "Muhammad Akhyar"
}